angular
  .module('pmr')
  .factory('userSeances',['users',function(users){
    var seances = {
      "pmr":[
        {
          date: (new Date(2015, 10, 18)),
          creneaux:[
            {
              debut: (new Date(2015, 10, 18)).setHours(9,0,0,0),
              fin:(new Date(2015, 10, 18)).setHours(10,50,0,0),
              participating:10,
              all:[
                {
                  id:"toto4",
                  pos:1,
                  pts:628
                },
                {
                  id:"toto10",
                  pos:2,
                  pts:620
                },
                {
                  id:"toto5",
                  pos:3,
                  pts:590
                },
                {
                  id:"toto3",
                  pos:4,
                  pts:400
                },
                {
                  id:"toto1",
                  pos:5,
                  pts:399
                },
                {
                  id:"pmr",
                  pos:6,
                  pts:368
                },
                {
                  id:"toto6",
                  pos:7,
                  pts:360
                },
                {
                  id:"toto7",
                  pos:8,
                  pts:344
                },
                {
                  id:"toto9",
                  pos:9,
                  pts:214
                },
                {
                  id:"toto2",
                  pos:10,
                  pts:200
                }
              ]
            },
            {
              debut: (new Date(2015, 10, 18)).setHours(18,30,0,0),
              fin:(new Date(2015, 10, 18)).setHours(20,45,0,0),
              participating:5,
              all:[
                {
                  id:"toto4",
                  pos:1,
                  pts:590
                },
                {
                  id:"pmr",
                  pos:2,
                  pts:490
                },
                {
                  id:"toto2",
                  pos:3,
                  pts:369
                },
                {
                  id:"toto1",
                  pos:4,
                  pts:361
                },
                {
                  id:"toto3",
                  pos:5,
                  pts:360
                }
              ]
            }
          ]
        },
        {
          date: (new Date(2015, 7, 12)),
          creneaux:[
            {
              debut: (new Date(2015, 7, 12)).setHours(11,30,0,0),
              fin:(new Date(2015, 7, 12)).setHours(12,30,0,0),
              participating:9,
              all:[
                {
                  id:"toto1",
                  pos:1,
                  pts:628
                },
                {
                  id:"toto2",
                  pos:2,
                  pts:620
                },
                {
                  id:"pmr",
                  pos:3,
                  pts:590
                },
                {
                  id:"toto3",
                  pos:4,
                  pts:400
                },
                {
                  id:"toto4",
                  pos:5,
                  pts:399
                },
                {
                  id:"toto5",
                  pos:6,
                  pts:368
                },
                {
                  id:"toto6",
                  pos:7,
                  pts:360
                },
                {
                  id:"toto7",
                  pos:8,
                  pts:344
                },
                {
                  id:"toto8",
                  pos:9,
                  pts:200
                }
              ]
            }
          ]
        }
      ]
    };
    return {
      all: () => { return seances; },
      get: function (){
        return seances[users.current()]?seances[users.current()]:[];
      }
    }
  }]);
